# Generated by Django 4.0.5 on 2022-10-05 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('avatar', models.ImageField(upload_to='files/avatar')),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(max_length=50)),
                ('title', models.CharField(default='0', max_length=200)),
                ('content', models.CharField(default='0', max_length=200)),
                ('link', models.CharField(default='', max_length=2083)),
                ('pic', models.ImageField(upload_to='files/post')),
                ('status', models.CharField(default='activate', max_length=15)),
                ('type', models.CharField(max_length=15)),
                ('votes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
