# Generated by Django 3.2.16 on 2022-11-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tree',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
