# Generated by Django 4.0.5 on 2022-10-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='v_flag',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
