# Generated by Django 4.0.5 on 2022-10-09 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_pic_alter_post_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='last_update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
