# Generated by Django 3.2.16 on 2022-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_of_upvote',
            field=models.IntegerField(default=0),
        ),
    ]
