# Generated by Django 4.0.5 on 2022-10-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_vote_last_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
