# Generated by Django 3.2.16 on 2022-11-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_total_of_upvote_post_best_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranks',
            name='controversial',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='hot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='new',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='raising',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ranks',
            name='top',
            field=models.FloatField(default=0),
        ),
    ]
