# Generated by Django 3.2.16 on 2022-11-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221111_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranks',
            new_name='Rank',
        ),
    ]
