# Generated by Django 3.2.16 on 2022-11-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_ranks_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='best',
            field=models.FloatField(default=0),
        ),
    ]
