# Generated by Django 3.2.16 on 2022-11-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_follow_followed_user_and_more'),
        ('api', '0014_alter_comment_content'),
    ]

    operations = [
    ]
