# Generated by Django 3.2.16 on 2022-11-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_merge_20221120_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_has_seen',
        ),
    ]
