# Generated by Django 3.2.16 on 2022-11-21 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_follow_followed_user_and_more'),
        ('api', '0015_merge_20221120_1450'),
    ]

    operations = [
    ]
