# Generated by Django 3.2.16 on 2022-11-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_notification_user_has_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, default='/test1.png', null=True, upload_to=''),
        ),
    ]
