# Generated by Django 3.2.16 on 2022-11-21 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20221121_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_has_seen',
        ),
    ]
